site_name: Wicked Adventures
site_url: https://vrednyj.github.io/Pipeline-testing/
repo_name: GitHub
docs_dir: doc/
nav:
    - Home: index.md
    - AutoDocs: autodoc.md
    - Back-end-testing: back-end-testing.md
    - Code: code.md
    - DAST: dast.md
    - Deployment: deployment.md
    - Installation: instalation.md
    - Front-end-testing: front-end-testing.md
    - Installation: installation.md
    - Monitoring: monitoring.md
    - SAST: sast.md
theme: readthedocs