name: Documentation Creation and Publishing
# Workflow triggers
on:
  # Code pushed to Dev branch will be a trigger
  push:
    branches: [ main ]      
  # Code pulled from Dev branch will be a trigger
  pull_request:
    branches: [ Dev ]

# build-job, package-job.
jobs:
  Publish-docs:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.9]

    steps:
    - name: Checkout code # checking our the code at current commit that triggers the workflow
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
   
        
    - name: Upgrading pip
      run: |
        python -m pip install --upgrade pip

    - name: Installing Dependencies and Setting up a Virtual Enviroment
      run: |
        python -m venv venv && source venv/bin/activate &&  pip install -r requirements.txt   

    - name: Exporting secret key
      run: |
        echo "SECRET_KEY = 'django-insecure-_^39%)wfp910i*)2!2+ihrxbnrv$&44nm#pv-yf!7&mqhbgnkz'" > .env

    - name: Run Migrations # run migrations to create table in side db container
      run: |
          source venv/bin/activate && python3.9 manage.py migrate
    
    - name: Automated Documention creation using Sphinx
      run: |
        cd doc && source ../venv/bin/activate && python ../venv/bin/sphinx-apidoc -f -d 8 -o . .. && make html && cd ..
   
    - name: Where are we?
      run: |
        ls
        tree
   
    - name: Publishing documents to gh-pages branch
      run: |
        pip install mkdocs
        git config user.name 'github-actions[bot]' && git config user.email 'github-actions[bot]@users.noreply.github.com'
        mkdocs gh-deploy --force
#        mkdocs gh-deploy --config-file mkdocs.yml --force
